### PR TITLE
Better app structure with npm package

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
this will allow easier workflow, when developing the app, things like live reload, ability to use es6 syntax ...

### CODE REVIEW

**Comment by Khaledgarbaya** [comment]
@mariobodemann here's the pull request, I will resolve the conflicts soon

**Comment by mariobodemann** [comment]
Those are a lot of changes, thank you! 

Any chance of explaining what is _better_ now, so my next JS will be less eye soring?

**Comment by Khaledgarbaya** [comment]
Tomorrow I will try to explain it

**Comment by Khaledgarbaya** [comment]
btw I can try to fix the conflicts if you grant me write access to your repo

**Comment by mariobodemann** [comment]
😓

**Pull request closed without merging**
